DROP SCHEMA IF EXISTS Shop;

CREATE SCHEMA IF NOT EXISTS Shop;

USE Shop;

CREATE TABLE Customer(
ID INT AUTO_INCREMENT PRIMARY KEY,
CustomerName VARCHAR(50),
Address VARCHAR(30),
Email VARCHAR(30),
Phone VARCHAR(12)
);

CREATE TABLE Orders(
ID INT AUTO_INCREMENT PRIMARY KEY,
OrderDate DATE,
Cost FLOAT,
CustomerID INT,
FOREIGN KEY (CustomerID) REFERENCES Customer(ID),
DeliveredStatus BOOL
);

CREATE TABLE Product(
ID INT AUTO_INCREMENT PRIMARY KEY,
ProductName VARCHAR(30),
Price FLOAT,
InStock INT Default 0
);

CREATE TABLE OrderProducts(
ID INT AUTO_INCREMENT PRIMARY KEY,
ProductID INT,
FOREIGN KEY (ProductID) REFERENCES Product(ID),
OrdersID INT,
FOREIGN KEY (OrdersID) REFERENCES Orders(ID)
);






